# Generated by Django 6.0 on 2026-02-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0002_contact_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
